language: node_js
node_js:
- '5'
notifications:
  webhooks:
    urls:
    - https://deploy-state.octoblu.com/deployments/travis-ci
    on_success: 'always'
    on_failure: 'always'
    on_start:   'always'
